<div class="cols marginBottom30 clearFix">
    <div class="col1-3">
        <h2 class="separate">Lorem ipsum dolor</h2>
        <div class="content withIcon icon1"><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus.</p></div>
    </div>
    <div class="col1-3">
        <h2 class="separate">Lorem ipsum dolor</h2>
        <div class="content withIcon icon2"><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus.</p></div>
    </div>
    <div class="col1-3">
        <h2 class="separate">Lorem ipsum dolor</h2>
        <div class="content withIcon icon3"><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus.</p></div>
    </div>
</div>
<hr>
<h2 class="separate">Lorem ipsum dolor</h2>
<div class="marginBottom30 clearFix">
    <div class="col1-4">
        <h3>Post title goes here</h3>
        <small class="date">by admin on Feb 3, 2011</small>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus.</p>
        <a href="./" class="more" title="View details">View details</a>
    </div>
    <div class="col3-4">
        <p class="gallery clearFix">
            <a class="photo" href="./" rel="gallery"><img src="/images/tmp/image1.png" alt="empty"></a>
            <a class="photo" href="./" rel="gallery"><img src="/images/tmp/image2.png" alt="empty"></a>
            <a class="photo" href="./" rel="gallery"><img src="/images/tmp/image3.png" alt="empty"></a>
        </p>
    </div>
</div>
<hr>
<h2 class="separate">Recent blog posts</h2>
<div class="marginBottom30 clearFix">
    <div class="col1-4">
        <h3>Post title goes here</h3>
        <small class="date">by admin on Feb 3, 2011</small>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus.</p>
    </div>
    <div class="col1-4">
        <h3>Post title goes here</h3>
        <small class="date">by admin on Feb 3, 2011</small>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus.</p>
    </div>
    <div class="col1-4">
        <h3>Post title goes here</h3>
        <small class="date">by admin on Feb 3, 2011</small>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus.</p>
    </div>
    <div class="col1-4">
        <h3>Post title goes here</h3>
        <small class="date">by admin on Feb 3, 2011</small>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus.</p>
    </div>
</div>
<p><a href="./" class="more" title="View blog">View blog</a></p>