<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php //echo $this->jQuery() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->headStyle() ?>
    </head>
    <body>
        <h1>Layout defaultowy  </h1>
        <?php echo $this->loggedInAs() ?>
        <?php echo $this->layout()->content ?>
        <?php echo $this->partial('_messenger.phtml') ?>
    </body>
</html>