<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Your PHP doc package
 * @subpackage Subpackage
 * @author     Paweł Grzeszczak <pgrzeszczak.mail@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends Base_User
{
    private static $_salt = "ag26";
    public function save()
    {
        // Tworzenie nowego użytkownika
        if (empty($this->id))
        {
            //haszowanie i solenie hasła
            $this->password = self::getHashedPassword($this->password);
        }
        parent::save();
    }
   /**
    * 
    *
    * @param string $sPassword
    * @return string
    */
    public static function getHashedPassword($sPassword)
    {
        return sha1($sPassword.self::$_salt);
    }
}