<h2><?php echo ucfirst($this->translate("list album")) ?></h2>
<?php if (!empty($this->oUser->Albums[0])): ?>
<table>
    <tr><th>Id</th><th><?php echo ucfirst($this->translate("name"))  ?></th><th><?php echo ucfirst($this->translate("action"))  ?></th></tr>
    <?php foreach ($this->oUser->Albums as $oAlbum): ?>
    <tr>
        <td><?php echo (int)$oAlbum->id ?></td>
        <td><a href="<?php echo $this->url(array('album_id'=>(int)$oAlbum->id), 'album_show') ?>"><?php echo $this->escape($oAlbum->name) ?></a></td>
        <td>
            <a href="<?php echo $this->url(array('album_id'=>(int)$oAlbum->id), 'album_edit') ?>">
                <img src="/images/ico/edit.png" alt="Edycja" />
            </a>
            <a href="<?php echo $this->url(array('album_id'=>(int)$oAlbum->id), 'album_delete') ?>">
                <img src="/images/ico/del.gif" alt="Usuwanie" />
            </a>
        </td>
    </tr>
    <?php endforeach ?>
</table>
<?php else: ?>
    <?php echo ucfirst($this->translate("you dont't have any album"))  ?>
<?php endif ?>
<a class="button" href="<?php echo $this->url(array(), 'album_add') ?>">
    <span><?php echo ucfirst($this->translate("add album")) ?></span>
</a>
