<script type="text/javascript">
$(document).ready( function() {
	$('#galery .photo a').lightBox();
});
</script>
<h1>Zawartość albumu</h1>
<div id="galery">

<?php if (!empty($this->Album->Photos[0]->id)): ?>
    <?php foreach ($this->Album->Photos as $oPhoto): ?>
    <a class="photo" href="<?php echo $oPhoto->Album->getDir().$oPhoto->getPhotoFileName() ?>" title="<?php echo $this->escape($oPhoto->description) ?>">
        <img alt="<?php echo $this->escape($oPhoto->description) ?>" src="<?php echo $oPhoto->Album->getDir().$oPhoto->getPhotoMinFileName() ?>">
    </a>
    <a href="<?php echo $this->url(array('photo_id'=>$oPhoto->id), 'photo_delete') ?>" title="Usuń obrazek">
        <img  alt="Usuń obrazek" src="">
    </a>
    <?php endforeach ?>
<?php else: ?>
    Pusty album
<?php endif ?>
</div>
<a href="<?php echo $this->url(array('album_id'=>$this->Album->id), 'photo_add', true) ?>">dodaj zdjęcie</a>
